### ISSUE TITLE
General edits in the project views (spelling issues)  

### ISSUE THREAD

**Issue by ishak52** [FACG5/BounceBack#181]
**We should fix these:**

* The page title spelling 
![dash](https://user-images.githubusercontent.com/34238574/48757325-05734700-eca5-11e8-9bba-600e6d8af1c0.png)
* The placeholder duplication words
![type](https://user-images.githubusercontent.com/34238574/48757395-3d7a8a00-eca5-11e8-9653-666f586a5764.png)
* Capitalize the words first letters in the labels  
![lables](https://user-images.githubusercontent.com/34238574/48757445-7450a000-eca5-11e8-9741-b0f63d6a0fe5.png)

**Comment by AsalaKM** [comment]
Done :smile:
