### ISSUE TITLE
Inconsistent formatting

### ISSUE THREAD

**Issue by maxgerber** [FACG5/BounceBack#187]
Me again!

As I was looking through all the repos, I also noticed that some of the merged code has inconsistent formatting. This suggests to me that not everyone's linters are set up correctly. Can you all double-check that your linters are working, and that eslint is autofixing on save, so that you don't have to worry about things extra spaces, incorrect indentation, or extra lines in your future PRs. Dedicating a little time to this now will make your code neater, easier to read, and more professional in the long run.

Thanks,
Max

**Comment by AsalaKM** [comment]
I solve this problem by re install the `es-lint` & check the `linter` work
:smile:
